services:
  rtmp:
    image: alfg/nginx-rtmp
    environment:
      - APP_HOSTNAME=localhost:9082
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template
      - rtmp:/rtmp
      - tmp:/tmp
    expose:
      - "1935"
      - "8080"
    ports:
      - "3935:1935"
      - "9080:8080"
    
  app:
    build: .
    environment:
      - STREAMING_SERVER_HOST=localhost
    expose:
      - "80"
    ports:
      - "9081:80"
    volumes:
      - rtmp:/rtmp
      - tmp:/tmp

volumes:
  rtmp:
  tmp: